export const AllAvailableTimesStyles = {
  container: {
    padding: 0,
  },
  headerSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: "10px",
    marginBottom: "32px",
  },
  headerTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    flexWrap: "wrap",
  },
  backButton: {
    textTransform: "none",
    color: "#666666",
    fontSize: "14px",
    padding: "8px 0",
    "&:hover": {
      backgroundColor: "transparent",
      color: "#155DFC",
    },
  },
  titleSection: {
    width: "100%",
  },
  mainTitle: {
    fontWeight: 600,
    fontSize: "24px",
    color: "#030C2B",
    marginBottom: "4px",
  },
  subtitle: {
    color: "#666666",
    fontSize: "14px",
  },
  addButton: {
    textTransform: "none",
    borderRadius: "8px",
    backgroundColor: "#155DFC",
    color: "#ffffff",
    padding: "10px 24px",
    fontSize: "14px",
    fontWeight: 500,
    "&:hover": {
      backgroundColor: "#1248d4",
    },
  },
  sortSection: {
    marginBottom: "24px",
    width: "100%",
    backgroundColor: "#ffffff",
    border: "1px solid #EAEAEA",
    borderRadius: "12px",
    padding: "12px 16px",
    boxShadow: "0px 2px 8px rgba(0, 0, 0, 0.06)",
  },
  sortGroup: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap",
  },
  filterIcon: {
    color: "#666666",
    fontSize: "20px",
  },
  sortLabel: {
    color: "#666666",
    fontSize: "14px",
    fontWeight: 500,
  },
  sortButton: {
    textTransform: "none",
    borderRadius: "8px",
    padding: "8px 16px",
    fontSize: "14px",
    fontWeight: 500,
    minWidth: "auto",
    "&.MuiButton-contained": {
      backgroundColor: "#155DFC",
      color: "#ffffff",
      "&:hover": {
        backgroundColor: "#1248d4",
      },
    },
    "&.MuiButton-outlined": {
      borderColor: "#E0E0E0",
      color: "#666666",
      backgroundColor: "#F5F5F5",
      "&:hover": {
        borderColor: "#BDBDBD",
        backgroundColor: "#E0E0E0",
      },
    },
  },
  timeSlotCard: {
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    border: "1px solid #EAEAEA",
    boxShadow: "0px 2px 8px rgba(0, 0, 0, 0.08)",
    marginBottom: "16px",
  },
  timeSlotContent: {
    padding: "20px",
    "&:last-child": {
      paddingBottom: "20px",
    },
  },
  timeSlotHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "16px",
    marginBottom: "10px",
  },
  timeSlotHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    flexWrap: "wrap",
    minWidth: 0,
  },
  timeSlotDate: {
    fontWeight: 600,
    fontSize: "16px",
    color: "#030C2B",
  },
  timeSlotDuration: {
    color: "#666666",
    fontSize: "14px",
  },
  timeSlotTime: {
    color: "#666666",
    fontSize: "14px",
    fontWeight: 500,
    marginBottom: "12px",
  },
  timeSlotLocation: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginBottom: "16px",
  },
  locationIcon: {
    color: "#1976d2",
    fontSize: "18px",
  },
  locationText: {
    color: "#1976d2",
    fontSize: "14px",
    fontWeight: 400,
  },
  timeSlotPrice: {
    fontWeight: 600,
    fontSize: "24px",
    color: "#4CAF50",
    lineHeight: 1,
    flexShrink: 0,
  },
  actionButtons: {
    display: "flex",
    gap: "12px",
    paddingTop: "16px",
    borderTop: "1px solid #E0E0E0",
  },
  editButton: {
    textTransform: "none",
    borderRadius: "8px",
    borderColor: "#E0E0E0",
    backgroundColor: "#F5F5F5",
    color: "#666666",
    padding: "8px 16px",
    fontSize: "14px",
    flex: 1,
    "&:hover": {
      borderColor: "#BDBDBD",
      backgroundColor: "#E0E0E0",
    },
  },
  deleteButton: {
    textTransform: "none",
    borderRadius: "8px",
    borderColor: "#F44336",
    backgroundColor: "#FFEBEE",
    color: "#F44336",
    padding: "8px 16px",
    fontSize: "14px",
    flex: 1,
    "&:hover": {
      borderColor: "#D32F2F",
      backgroundColor: "#FFDDE2",
    },
  },
};
