export const SessionProfileStyles = {
  container: {
    padding: 0,
  },
  card: {
    borderRadius: '12px',
    boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.08)',
    backgroundColor: '#ffffff',
    marginBottom: '24px',
    '&:last-child': {
      marginBottom: 0,
    },
  },
  cardContent: {
    padding: '24px',
    '&:last-child': {
      paddingBottom: '24px',
    },
  },
  profileHeader: {
    display: 'flex',
    gap: '24px',
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: '8px',
    objectFit: 'cover',
    display: 'block',
  },
  profileInfo: {
    flex: 1,
  },
  name: {
    fontWeight: 600,
    marginBottom: '8px',
    color: '#030C2B',
    fontSize: '24px',
  },
  title: {
    color: '#666666',
    marginBottom: '16px',
    fontWeight: 500,
    fontSize: '18px',
  },
  metaInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  metaItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: '#666666',
  },
  metaIcon: {
    fontSize: '20px',
    color: '#666666',
  },
  sectionTitle: {
    fontWeight: 600,
    fontSize: '18px',
    color: '#030C2B',
    marginBottom: '16px',
    lineHeight: 1.5,
  },
  educationHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
  },
  aboutText: {
    color: '#666666',
    lineHeight: 1.7,
    fontSize: '14px',
  },
  expertiseContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  expertiseChip: {
    backgroundColor: '#FAFAFA',
    color: '#666666',
    fontWeight: 500,
    fontSize: '14px',
    height: '36px',
    borderRadius: '6px',
    padding: '0 16px',
    border: '1px solid #E0E0E0',
    '& .MuiChip-label': {
      padding: '0',
    },
    '& .MuiChip-deleteIcon': {
      fontSize: '16px',
      color: '#666666',
      margin: '0 0 0 8px',
      '&:hover': {
        color: '#030C2B',
      },
    },
  },
  educationTimeline: {
    position: 'relative',
    paddingLeft: '32px',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    '&::before': {
      content: '""',
      position: 'absolute',
      left: '8px',
      top: '0',
      bottom: '0',
      width: '2px',
      backgroundColor: '#030C2B',
    },
  },
  educationItem: {
    position: 'relative',
    display: 'flex',
    alignItems: 'flex-start',
    padding: 0,
    marginBottom: 0,
    minHeight: '48px',
    width: '100%',
    '&:last-child': {
      marginBottom: 0,
    },
  },
  educationItemEdit: {
    position: 'relative',
    display: 'flex',
    alignItems: 'flex-start',
    padding: '16px',
    marginBottom: '16px',
    minHeight: 'auto',
    width: '100%',
    border: '1px solid #e0e0e0',
    borderRadius: '8px',
    backgroundColor: '#ffffff',
    '&:last-child': {
      marginBottom: 0,
    },
  },
  timelineDot: {
    position: 'absolute',
    left: '-32px',
    top: '0.35em', // Center with first line of text
    width: '16px',
    height: '16px',
    borderRadius: '50%',
    backgroundColor: '#E0E0E0',
    border: 'none',
    zIndex: 2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transform: 'translateY(-50%)', // Center vertically
    '&::after': {
      content: '""',
      width: '6px',
      height: '6px',
      borderRadius: '50%',
      backgroundColor: '#030C2B',
    },
  },
  educationContent: {
    flex: 1,
  },
  educationDegree: {
    fontWeight: 400,
    color: '#666666',
    fontSize: '14px',
    lineHeight: 1.6,
    marginBottom: '4px',
  },
  educationUniversity: {
    color: '#999999',
    fontSize: '14px',
    fontWeight: 400,
  },
  editProfileButton: {
    textTransform: 'none',
    borderRadius: '8px',
    backgroundColor: '#1976d2',
    color: '#ffffff',
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: 500,
    marginBottom: '24px',
    '&:hover': {
      backgroundColor: '#1565c0',
    },
  },
  availableSessionsCard: {
    borderRadius: '12px',
    boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.08)',
    backgroundColor: '#E3F2FD',
    marginBottom: '24px',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  cardHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  cardIcon: {
    color: '#666666',
    fontSize: '20px',
  },
  cardTitle: {
    fontWeight: 600,
    color: '#030C2B',
    fontSize: '18px',
  },
  subtitleContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '16px',
  },
  subtitleIcon: {
    color: '#666666',
    fontSize: '16px',
  },
  subtitle: {
    color: '#666666',
    fontWeight: 500,
    fontSize: '14px',
  },
  sessionsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginBottom: '16px',
    maxHeight: '500px', // Approximately 5 sessions tall
    overflowY: 'auto',
    overflowX: 'hidden',
    paddingRight: '8px',
    // Custom scrollbar styling
    '&::-webkit-scrollbar': {
      width: '8px',
    },
    '&::-webkit-scrollbar-track': {
      background: '#f1f1f1',
      borderRadius: '4px',
    },
    '&::-webkit-scrollbar-thumb': {
      background: '#c1c1c1',
      borderRadius: '4px',
      '&:hover': {
        background: '#a8a8a8',
      },
    },
  },
  sessionSlot: {
    padding: '16px',
    backgroundColor: '#FFFFFF',
    borderRadius: '8px',
    border: '1px solid #E0E0E0',
    boxShadow: '0px 1px 3px rgba(0, 0, 0, 0.1)',
  },
  sessionSlotTopRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  sessionDay: {
    fontWeight: 600,
    color: '#030C2B',
    fontSize: '14px',
  },
  sessionDot: {
    color: '#666666',
    fontSize: '14px',
  },
  sessionDuration: {
    color: '#999999',
    fontSize: '14px',
  },
  sessionTime: {
    color: '#030C2B',
    fontSize: '14px',
    marginBottom: '8px',
  },
  sessionLocation: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  locationIcon: {
    color: '#1976d2',
    fontSize: '16px',
  },
  locationText: {
    color: '#1976d2',
    fontSize: '14px',
    textDecoration: 'underline',
    '&:hover': {
      textDecoration: 'underline',
    },
  },
  sessionPrice: {
    fontWeight: 600,
    color: '#4CAF50',
    fontSize: '14px',
  },
  sessionButtons: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  viewAllButton: {
    textTransform: 'none',
    borderRadius: '8px',
    borderColor: '#B3E5FC',
    color: '#1976d2',
    backgroundColor: '#FFFFFF',
    padding: '10px 16px',
    fontSize: '14px',
    fontWeight: 500,
    '&:hover': {
      backgroundColor: '#F5F5F5',
      borderColor: '#81D4FA',
    },
    '& .MuiSvgIcon-root': {
      color: '#1976d2',
    },
  },
  viewAgendaButton: {
    textTransform: 'none',
    borderRadius: '8px',
    borderColor: '#B3E5FC',
    color: '#1976d2',
    backgroundColor: '#FFFFFF',
    padding: '10px 16px',
    fontSize: '14px',
    fontWeight: 500,
    '&:hover': {
      backgroundColor: '#F5F5F5',
      borderColor: '#81D4FA',
    },
    '& .MuiSvgIcon-root': {
      color: '#1976d2',
    },
  },
  contactSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  contactItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  contactIcon: {
    color: '#666666',
    fontSize: '20px',
  },
  contactLink: {
    color: '#1976d2',
    textDecoration: 'none',
    fontSize: '14px',
    '&:hover': {
      textDecoration: 'underline',
    },
  },
  profileEditContainer: {
    display: 'flex',
    gap: '24px',
    alignItems: 'flex-start',
  },
  avatarWrapper: {
    position: 'relative',
    display: 'inline-block',
    width: 'fit-content',
    flexShrink: 0,
  },
  profileAvatar: {
    width: 150,
    height: 150,
    borderRadius: '8px',
  },
  profilePictureSection: {
    marginBottom: '24px',
    display: 'flex',
    justifyContent: 'flex-start',
  },
  cameraButton: {
    position: 'absolute',
    bottom: '0',
    right: '0',
    backgroundColor: '#155DFC',
    border: '2px solid #ffffff',
    width: '36px',
    height: '36px',
    padding: 0,
    transform: 'translate(25%, 25%)',
    boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.15)',
    borderRadius: '50%',
    '&:hover': {
      backgroundColor: '#1248d4',
    },
    '& .MuiSvgIcon-root': {
      fontSize: '18px',
      color: '#ffffff',
    },
  },
  formSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    flex: 1,
  },
  textField: {
    '& .MuiOutlinedInput-root': {
      borderRadius: '8px',
      backgroundColor: '#ffffff',
      '& fieldset': {
        borderColor: '#E0E0E0',
        borderWidth: '1px',
      },
      '&:hover fieldset': {
        borderColor: '#BDBDBD',
      },
      '&.Mui-focused fieldset': {
        borderColor: '#155DFC',
        borderWidth: '1px',
      },
    },
    '& .MuiInputLabel-root': {
      color: '#666666',
      fontSize: '14px',
      fontWeight: 400,
      '&.Mui-focused': {
        color: '#155DFC',
      },
    },
    '& .MuiOutlinedInput-input': {
      padding: '12px 14px',
      fontSize: '14px',
      color: '#030C2B',
      fontWeight: 400,
    },
  },
  sessionsCompletedField: {
    '& .MuiOutlinedInput-root': {
      borderRadius: '8px',
      backgroundColor: '#F5F5F5',
      '& fieldset': {
        borderColor: '#E0E0E0',
        borderWidth: '1px',
      },
      '&.Mui-disabled': {
        backgroundColor: '#F5F5F5',
        '& fieldset': {
          borderColor: '#E0E0E0',
        },
      },
    },
    '& .MuiInputLabel-root': {
      color: '#666666',
      fontSize: '14px',
      fontWeight: 400,
      '&.Mui-disabled': {
        color: '#999999',
      },
    },
    '& .MuiOutlinedInput-input': {
      padding: '12px 14px',
      fontSize: '14px',
      color: '#666666',
      fontWeight: 400,
    },
  },
  updatedText: {
    color: '#999999',
    fontSize: '12px',
    marginTop: '-4px',
    fontStyle: 'normal',
    fontWeight: 400,
  },
  addExpertiseContainer: {
    display: 'flex',
    gap: '12px',
    alignItems: 'flex-start',
    marginTop: '16px',
  },
  expertiseInput: {
    flex: 1,
    '& .MuiOutlinedInput-root': {
      borderRadius: '8px',
      backgroundColor: '#ffffff',
      '& fieldset': {
        borderColor: '#e0e0e0',
      },
      '&:hover fieldset': {
        borderColor: '#bdbdbd',
      },
      '&.Mui-focused fieldset': {
        borderColor: '#1976d2',
      },
    },
    '& .MuiOutlinedInput-input': {
      padding: '8px 12px',
      fontSize: '14px',
      color: '#333333',
    },
  },
  addButton: {
    textTransform: 'none',
    borderRadius: '8px',
    backgroundColor: '#155DFC',
    color: '#ffffff',
    padding: '8px 24px',
    minWidth: '80px',
    fontSize: '14px',
    fontWeight: 500,
    height: '40px',
    '&:hover': {
      backgroundColor: '#1248d4',
    },
  },
  chipDeleteIcon: {
    fontSize: '16px',
    color: '#666666',
    margin: '0 0 0 8px',
    '&:hover': {
      color: '#030C2B',
    },
  },
  removeButton: {
    position: 'absolute',
    top: '8px',
    right: '8px',
    color: '#f44336',
    padding: '0',
    width: '24px',
    height: '24px',
    minWidth: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    border: '1px solid #e0e0e0',
    borderRadius: '50%',
    zIndex: 10,
    '&:hover': {
      backgroundColor: '#ffebee',
      borderColor: '#f44336',
    },
    '& .MuiSvgIcon-root': {
      fontSize: '14px',
      margin: 0,
    },
  },
  addEducationButton: {
    textTransform: 'none',
    borderRadius: '8px',
    backgroundColor: '#155DFC',
    color: '#ffffff',
    padding: '8px 16px',
    fontSize: '14px',
    fontWeight: 500,
    '&:hover': {
      backgroundColor: '#1248d4',
    },
    '& .MuiSvgIcon-root': {
      fontSize: '18px',
    },
  },
  uploadBox: {
    border: '2px dashed #e0e0e0',
    borderRadius: '8px',
    padding: '32px 24px',
    textAlign: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fafafa',
    '&:hover': {
      borderColor: '#1976d2',
      backgroundColor: '#f5f5f5',
    },
  },
  uploadIcon: {
    fontSize: '48px',
    color: '#999999',
    marginBottom: '8px',
  },
  uploadText: {
    color: '#666666',
    fontWeight: 500,
    fontSize: '14px',
    marginBottom: '4px',
  },
  uploadSubtext: {
    color: '#999999',
    fontSize: '12px',
  },
  cancelButton: {
    textTransform: 'none',
    borderRadius: '8px',
    color: '#666666',
    borderColor: '#e0e0e0',
    padding: '10px 24px',
    fontSize: '14px',
    fontWeight: 500,
    minWidth: '100px',
    '&:hover': {
      borderColor: '#bdbdbd',
      backgroundColor: '#f5f5f5',
    },
  },
  saveButton: {
    textTransform: 'none',
    borderRadius: '8px',
    backgroundColor: '#155DFC',
    color: '#ffffff',
    padding: '10px 24px',
    fontSize: '14px',
    fontWeight: 500,
    minWidth: '140px',
    '&:hover': {
      backgroundColor: '#1248d4',
    },
  },
  actionButtonsContainer: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    marginBottom: '24px',
  },
}
