export const CertificationStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  toolbarCard: {
    borderRadius: '12px',
    border: '1px solid #EAEAEA',
    boxShadow: 'none',
  },
  toolbarCardContent: {
    padding: '24px',
    '&:last-child': {
      paddingBottom: '24px',
    },
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '16px',
  },
  title: {
    fontWeight: 600,
    fontSize: '18px',
    color: '#030C2B',
  },
  headerActions: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  },
  actionButton: {
    textTransform: 'none',
    borderRadius: '8px',
    borderColor: '#E0E0E0',
    backgroundColor: '#ffffff',
    '&:hover': {
      borderColor: '#BDBDBD',
      backgroundColor: '#F5F5F5',
    },
  },
  toolbar: {
    display: 'flex',
    gap: '12px',
    marginTop: '14px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  searchField: {
    flex: 1,
    minWidth: '200px',
    maxWidth: '720px',
    '& .MuiOutlinedInput-root': {
      borderRadius: '8px',
    },
  },
  searchIcon: {
    color: '#666666',
  },
  downloadAllButton: {
    textTransform: 'none',
    borderRadius: '10px',
    backgroundColor: '#155DFC',
    color: '#ffffff',
    padding: '10px 18px',
    '&:hover': {
      backgroundColor: '#1248d4',
    },
  },
  stats: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  statsText: {
    fontWeight: 500,
    color: '#030C2B',
  },
  activityContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: '#666666',
  },
  activityIcon: {
    fontSize: '18px',
    color: '#666666',
  },
  activityText: {
    color: '#666666',
    fontSize: '14px',
  },
  certificateCard: {
    borderRadius: '12px',
    border: '1px solid #EAEAEA',
    boxShadow: 'none',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
  cardContent: {
    padding: '24px',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  cardTopRow: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '12px',
    marginBottom: '16px',
  },
  cardTopLeft: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    minWidth: 0,
  },
  checkCircle: {
    width: 36,
    height: 36,
    borderRadius: '10px',
    backgroundColor: '#E8F5E9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  checkIcon: {
    fontSize: '20px',
    color: '#008236',
  },
  statusChip: {
    backgroundColor: '#E8F5E9',
    color: '#008236',
    fontWeight: 600,
    fontSize: '12px',
    height: '24px',
    borderRadius: '12px',
    '& .MuiChip-label': {
      padding: '0 10px',
    },
  },
  programName: {
    fontWeight: 600,
    fontSize: '14px',
    color: '#030C2B',
    lineHeight: 1.3,
  },
  mentorRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginTop: '6px',
  },
  mentorIcon: {
    fontSize: '16px',
    color: '#666666',
  },
  mentorName: {
    fontSize: '13px',
    color: '#666666',
    fontWeight: 500,
  },
  studentRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '14px 16px',
    borderRadius: '10px',
    backgroundColor: '#F8FAFC',
    border: '1px solid #EEF2F7',
    marginBottom: '14px',
  },
  studentLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  studentAvatar: {
    width: 34,
    height: 34,
    borderRadius: '50%',
    backgroundColor: '#0F5F8A',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  studentAvatarIcon: {
    fontSize: '20px',
    color: '#ffffff',
  },
  studentLabel: {
    fontSize: '12px',
    color: '#666666',
    fontWeight: 600,
    marginBottom: '2px',
  },
  studentName: {
    fontSize: '14px',
    color: '#030C2B',
    fontWeight: 600,
  },
  studentRight: {
    textAlign: 'right',
  },
  studentIdLabel: {
    fontSize: '12px',
    color: '#666666',
    fontWeight: 600,
    marginBottom: '2px',
  },
  studentIdValue: {
    fontSize: '14px',
    color: '#030C2B',
    fontWeight: 700,
  },
  dateRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    paddingBottom: '14px',
  },
  dateItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flex: 1,
    minWidth: 0,
  },
  durationItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    minWidth: '100px',
  },
  dateIcon: {
    fontSize: '18px',
    color: '#666666',
  },
  dateLabel: {
    fontSize: '12px',
    color: '#666666',
    fontWeight: 600,
    marginBottom: '2px',
  },
  dateValue: {
    fontSize: '14px',
    color: '#030C2B',
    fontWeight: 700,
  },
  cardActions: {
    display: 'flex',
    gap: '8px',
    marginTop: 'auto',
    paddingTop: '16px',
    borderTop: '1px solid #e0e0e0',
  },
  viewButton: {
    textTransform: 'none',
    borderRadius: '8px',
    backgroundColor: '#030C2B',
    color: '#ffffff',
    flex: 1,
    '&:hover': {
      backgroundColor: '#1a1a2e',
    },
  },
  iconButton: {
    color: '#030C2B',
    border: '1px solid #E0E0E0',
    borderRadius: '8px',
    '&:hover': {
      backgroundColor: '#f5f5f5',
    },
  },

  // Preview dialog
  previewDialogPaper: {
    borderRadius: '12px',
    overflow: 'hidden',
  },
  previewDialogContent: {
    padding: '16px',
    position: 'relative',
  },
  previewCloseButton: {
    position: 'absolute',
    top: '14px',
    right: '14px',
    zIndex: 2,
    backgroundColor: '#ffffff',
    border: '1px solid #E0E0E0',
    '&:hover': {
      backgroundColor: '#F5F5F5',
    },
  },
  certificatePreview: {
    width: '100%',
    // match the reference image proportions (approx 2048x1742)
    maxWidth: { xs: '94vw', sm: '860px', md: '980px' },
    aspectRatio: '2048 / 1742',
    height: 'auto',
    margin: '0 auto',
    borderRadius: '10px',
    border: '1px solid #E0E0E0',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#ffffff',
  },
  certificateBody: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    width: '100%',
    position: 'relative',
  },
  certificateFooter: {
    height: { xs: 74, md: 86 },
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: '16px',
    padding: { xs: '10px 14px', md: '12px 22px' },
    borderTop: '1px solid #EAEAEA',
    backgroundColor: '#ffffff',
    position: 'relative',
    zIndex: 0,
  },
  previewFooterNote: {
    fontSize: { xs: '10px', md: '12px' },
    color: '#9A9A9A',
    textAlign: 'center',
    maxWidth: { xs: '70%', md: '68%' },
    lineHeight: 1.35,
  },
  previewFooterVerify: {
    position: 'absolute',
    right: { xs: 14, md: 22 },
    bottom: { xs: 10, md: 12 },
    textAlign: 'right',
  },
  previewLeft: {
    flex: 1,
    backgroundColor: '#ffffff',
    padding: { xs: '22px 22px', md: '34px 46px' },
    position: 'relative',
    // subtle watermark pattern like the reference
    backgroundImage:
      'repeating-linear-gradient(135deg, rgba(3, 12, 43, 0.03) 0px, rgba(3, 12, 43, 0.03) 26px, rgba(255,255,255,0) 26px, rgba(255,255,255,0) 66px)',
    backgroundSize: 'auto',
  },
  previewLogoRow: {
    display: 'flex',
    justifyContent: 'center',
    marginBottom: '18px',
  },
  previewLogo: {
    width: { xs: '150px', md: '170px' },
    height: 'auto',
  },
  previewDate: {
    fontSize: '12px',
    color: '#666666',
    marginBottom: '12px',
  },
  previewStudentName: {
    fontSize: { xs: '34px', md: '44px' },
    fontWeight: 800,
    color: '#030C2B',
    lineHeight: 1.1,
    marginBottom: '10px',
  },
  previewSubtext: {
    fontSize: '14px',
    color: '#666666',
    marginBottom: '18px',
  },
  previewProgramName: {
    fontSize: { xs: '18px', md: '22px' },
    fontWeight: 800,
    color: '#030C2B',
    marginBottom: '16px',
  },
  previewMentor: {
    fontSize: '12px',
    color: '#666666',
    marginBottom: '26px',
  },
  previewSignatureBlock: {
    position: 'absolute',
    left: { xs: 22, md: 42 },
    bottom: { xs: 22, md: 32 },
    right: '45%',
  },
  previewSignatureLine: {
    height: '1px',
    width: '260px',
    backgroundColor: '#DADADA',
    marginBottom: '10px',
  },
  previewSignatureName: {
    fontSize: '12px',
    color: '#030C2B',
    fontWeight: 600,
  },
  previewSignatureTitle: {
    fontSize: '11px',
    color: '#666666',
  },
  previewRight: {
    width: { xs: '36%', md: '30%' },
    background: 'linear-gradient(180deg, #2AA7D3 0%, #0F5F8A 100%)',
    padding: { xs: '26px 18px', md: '36px 22px' },
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
    // extend into the footer and create the notch like the reference
    marginBottom: { xs: '-74px', md: '-86px' },
    paddingBottom: { xs: '74px', md: '86px' },
    zIndex: 1,
    clipPath: 'polygon(0 0, 100% 0, 100% 86%, 50% 100%, 0 86%)',
  },
  previewRightTitleTop: {
    fontSize: '11px',
    letterSpacing: '2px',
    color: '#D9F2FF',
    marginTop: '10px',
  },
  previewRightTitle: {
    fontSize: '16px',
    letterSpacing: '2px',
    fontWeight: 700,
    color: '#ffffff',
    marginTop: '6px',
  },
  previewSeal: {
    marginTop: '26px',
    width: { xs: 150, md: 170 },
    height: { xs: 150, md: 170 },
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewSealOuterRing: {
    width: '100%',
    height: '100%',
    borderRadius: '50%',
    backgroundColor: '#ffffff',
    border: '3px solid rgba(0,0,0,0.22)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: { xs: '12px', md: '14px' },
    textAlign: 'center',
  },
  previewSealOuterText: {
    fontSize: { xs: '9px', md: '10px' },
    color: '#666666',
    letterSpacing: '0.6px',
    lineHeight: 1.15,
  },
  previewSealInnerRing: {
    marginTop: '10px',
    border: '1px solid #DCDCDC',
    borderRadius: '50%',
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: { xs: '9px', md: '10px' },
  },
  previewSealBrand: {
    fontSize: '10px',
    fontWeight: 800,
    color: '#155DFC',
    marginBottom: '6px',
  },
  previewSealRingText: {
    fontSize: '9px',
    color: '#666666',
    letterSpacing: '1px',
  },
  previewVerify: {
    fontSize: '10px',
    color: '#9A9A9A',
  },
  previewVerifyLink: {
    fontSize: '10px',
    color: '#155DFC',
    fontWeight: 600,
  },
}
